### ISSUE TITLE
Integrate with a real git repository

### ISSUE THREAD

**Issue by leonsoft** [nicoespeon/gitgraph.js#123] opened 2016-11-04 01:35 UTC
I like the graph (blackarrow) very much.  
But I do not want to call API like _gitgraph.commit("My first commit")._   
I hople it reads the .git folder/url and renders the graph in a web page or desktop app.  
Is that possible? Thanks.

**Comment by nicoespeon** [comment] 2016-11-04 16:30
Hello @leonsoft!

What you ask looks like #117, which is not yet implemented. Am I correct?

Also, there was an ambition to render the graph from a JSON, but I never find the time / motivation to do that.

**Comment by nicoespeon** [comment] 2016-12-04 12:22
Hi @leonsoft!

Thanks again for your suggestion.
After checking other issues, I definitely understand that as a duplicate of #117.

I'm closing it as a duplicate since this need is supported with the other issue 👌

**Closed by nicoespeon** 2016-12-04 12:22 UTC
Labels: duplicate
