### ISSUE TITLE
develop.merge(feature) should always merge feature into develop

### ISSUE THREAD

**Issue by briangordon** [nicoespeon/gitgraph.js#261] opened 2019-04-10 03:23 UTC
It seems that sometimes `develop.merge(feature)` can actually cause develop to be merged into feature rather than the other way around. This is counter to the way that it usually works. This seems similar to #175, and I'm confused because it looks like gitgraph used to be *intended* to work the other way around, based on the codepen. However, either way it's supposed to work, gitgraph doesn't correctly render this pretty simple case where you continue committing to a branch after merging it:

```
      {(gitgraph) => {
        const develop = gitgraph.branch("develop");
        develop.commit();
        const feature = gitgraph.branch("feature");
        feature.commit();
        develop.merge(feature);
        feature.commit();
        develop.merge(feature);
      }}
```

<img width="409" alt="screenshot" src="https://user-images.githubusercontent.com/1331024/55849386-41e4f980-5b05-11e9-82c8-59e2c5540481.png">

Or, the other way around,

``` 
     {(gitgraph) => {
        const develop = gitgraph.branch("develop");
        develop.commit();
        const feature = gitgraph.branch("feature");
        feature.commit();
        feature.merge(develop);
        feature.commit();
        feature.merge(develop);
      }}
```

<img width="411" alt="screenshot-1" src="https://user-images.githubusercontent.com/1331024/55849392-45788080-5b05-11e9-9369-f3c61ce18a9e.png">

**Comment by nicoespeon** [comment] 2019-04-12 00:53
> I'm confused because it looks like gitgraph used to be intended to work the other way around

Yes. Actually, the first version of Gitgraph (which is the package `gitgraph.js`) used to do it the other way around. `develop.merge(feature)` would merge `develop` into `feature`. 

We found that it was confusing. With git, we would checkout to `develop` to merge `feature` into it, so `develop.merge(feature)` should express merging `feature` into `develop` (the branch we're in).

We explained this breaking change here: https://github.com/nicoespeon/gitgraph.js/blob/master/packages/gitgraph-js/MIGRATE_FROM_GITGRAPH.JS.md#merges

---

Now, regarding the examples you provided, I can see that the merge commit is on the correct branch every time. The problem is the branch path which looks wrong.

In fact, it reminds me of https://github.com/nicoespeon/gitgraph.js/issues/251 => branch path was wrongly calculated when there was a commit on the same branch after it was merged. 

We fixed it and you can install the latest version of the rendering lib you use to solve this issue I think 👍 

For example, for the first scenario in `VerticalReverse` orientation, here's the resulting graph:

![image](https://user-images.githubusercontent.com/1094774/56004875-8c987a00-5c9b-11e9-8f84-9cb11a32fe20.png)

And the second:

![image](https://user-images.githubusercontent.com/1094774/56004893-a20da400-5c9b-11e9-8e7e-841a747b51b6.png)

As I think this issue has been fixed with #251, I'm closing this one. 
Thanks for creating detailed issues like this, it's really helpful =)

**Closed by nicoespeon** 2019-04-12 00:53 UTC
