### ISSUE TITLE
branch.showLabel causes line to extend after branch line/curve

### ISSUE THREAD

**Issue by drichter9293** [nicoespeon/gitgraph.js#177] opened 2017-10-07 00:38 UTC
As seen in the example below, when creating a new branch with a label, the branch curve is the correct length, but a straight line is inserted directly after, before the first commit of branch1. However, for the unlabeled branch, there is no extra line. Is there a way to remove this extra line when using a label?

https://jsfiddle.net/drichter9293/Lg80wjd1/

**Comment by nicoespeon** [comment] 2017-10-09 07:48
That's right, I do think this can be removed even if the label is overlapping the line − which may have been the reason behind this extra line, but I can't remember for sure 🤔

**Comment by yodalee** [comment] 2017-12-23 18:43
I locate the reason of this extended:
https://github.com/nicoespeon/gitgraph.js/blob/develop/src/gitgraph.js#L782-L783
It seems that extended line is added to let label overlap the line.

**Comment by nicoespeon** [comment] 2018-08-31 02:59
For later resolution, here's a playground showing the issue: https://codepen.io/nicoespeon/pen/qMRZXg?editors=0010

![image](https://user-images.githubusercontent.com/1094774/44890428-39dbf600-aca8-11e8-8cfc-4efd0214e5bd.png)

The problem is that `branch1` is pushed to the right with a straight line, while the second branch is not. The difference is that we show the label of `branch1`.

**Comment by nicoespeon** [comment] 2019-02-10 03:04
So, this is technically _not_ resolved for the `gitgraph.js` package… But we released `@gitgraph/react` in v1.0.0-0 and this issue was fixed here.

Thus, I'm closing this issue as we won't maintain the `gitgraph.js` package. There will be a `@gitgraph/js` package soon to replace it. 

We still accept PRs if someone really needs it, but I'd suggest moving to the aforementioned packages. Thanks 🙏

**Closed by nicoespeon** 2019-02-10 03:04 UTC
Labels: :bug: Bug
