### ISSUE TITLE
undefined branch -- import fails on git2json blob

### ISSUE THREAD

**Issue by dimaqq** [nicoespeon/gitgraph.js#228] opened 2019-02-12 06:09 UTC
```
TypeError: Cannot read property 'style' of undefined
    at eval (gitgraph.js:88)
    at Array.forEach (<anonymous>)
    at GitgraphCore.getRenderedData (gitgraph.js:83)
    at Gitgraph.onGitgraphCoreRender (Gitgraph.js:152)
    at eval (gitgraph.js:179)
    at Array.forEach (<anonymous>)
    at GitgraphCore.next (gitgraph.js:178)
    at GitgraphCore._import (gitgraph.js:237)
    at Object.eval [as children] (App.js:32)
    at Gitgraph.componentDidMount (Gitgraph.js:56)
    at commitLifeCycles (react-dom.development.js:17636)
    at commitAllLifeCycles (react-dom.development.js:19141)
    at HTMLUnknownElement.callCallback (react-dom.development.js:147)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:196)
    at invokeGuardedCallback (react-dom.development.js:250)
    at commitRoot (react-dom.development.js:19360)
    at completeRoot (react-dom.development.js:20893)
    at performWorkOnRoot (react-dom.development.js:20816)
    at performWork (react-dom.development.js:20721)
    at performSyncWork (react-dom.development.js:20695)
    at requestWork (react-dom.development.js:20550)
    at scheduleWork (react-dom.development.js:20357)
    at Object.enqueueSetState (react-dom.development.js:11475)
    at App.Component.setState (react.development.js:336)
    at App._callee$ (App.js:19)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:282)
    at Generator.prototype.(:3000/anonymous function) [as next] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:116:21)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
```

Data: https://gist.github.com/dimaqq/a9122f28e9807527508056ee32d719cd

**Comment by nicoespeon** [comment] 2019-02-14 13:53
Thanks for the data snippet, that will be really helpful for us to debug what is happening here 👍

**Comment by nicoespeon** [comment] 2019-03-07 04:07
Hey @dimaqq 👋 

I gave it a look and I can't reproduce the issue with the latest version on master.

With the following code:

```tsx
import { Gitgraph } from "@gitgraph/react";

<Gitgraph>
    {(gitgraph) => {
        const oneCommit = [
          {
            refs: ["tag: 0.1"],
            hash: "6bf194888b1c0e40d68aae9424c69e798395b165",
            hashAbbrev: "6bf1948",
            tree: "37097d59d05d6216edb082f62ce15be4eb6b732d",
            treeAbbrev: "37097d5",
            parents: [],
            parentsAbbrev: [],
            author: {
              name: "xxxxxxxxxxxx",
              email: "xxxxxxxxxxxx@xxxxxxxxx",
              timestamp: 1494385923000,
            },
            committer: {
              name: "xxxxxxxxxxxx",
              email: "xxxxxxxxxxxx@xxxxxxxxx",
              timestamp: 1494385923000,
            },
            subject: "initial commit",
            body: "",
            notes: "",
            stats: [],
          },
        ];
        gitgraph.import(oneCommit);
    }}
</Gitgraph>
```

I got the following result:

![image](https://user-images.githubusercontent.com/1094774/53931727-6102ee00-4064-11e9-902b-e7129a630a58.png)

Could you try again with the latest version of `@gitgraph/react` see how it goes?
Thanks 🙏 

Meanwhile, I'm closing the issue since I can't reproduce. But feel free to re-open or create a new one if you have a bug.

**Closed by nicoespeon** 2019-03-07 04:07 UTC
Labels: :bug: Bug, 🎷 @gitgraph/core
