### ISSUE TITLE
Checkout on a commit

### ISSUE THREAD

**Issue by alvassin** [nicoespeon/gitgraph.js#248] opened 2019-03-29 10:42 UTC
I can checkout on a branch, but is it possible to checkout on some previous commit?

**Comment by nicoespeon** [comment] 2019-03-31 15:07
Unfortunately, not at the moment. You can only checkout a branch. 

This might be something interesting though. Could you share more details about what you'd like to achieve? Do you have a use-case in mind that would require you to checkout a specific commit instead of a branch?

**Comment by alvassin** [comment] 2019-04-03 07:30
I am implementing simple git-like versioning system over postgres. I has commits and branches inside, as user you are able to derive from any commit tied to any branch.

First idea was to get response from API in format like git2json and use your `import` function from react package. 
But I can deal only Vuejs, not familiar with React and it was too hard to adopt your react package for Vuejs for me.

So, i tried to make similar API to git2json in my backend and use your gitgraph.js package to draw graph by myself using commands like `graph.commit`, `graph.branch` and `graph.merge`.

My commits are represented auto-incrementing integers, so i just iterate from 1 to latest one and doing the following in the loop:
- Graph is empty, we are processing first commit
  - Create branch and commit current commit
- Commit has one parent commit
  - If branch for current commit does not exist in graph - create new branch, deriving from parent commits' branch.
  - If branch for current commit exists - call checkout for that branch
  - Commit current commit
- Commit has two parent commits
  - Find parent commit with different branch, checkout to this branch
  - Merge to the current commit branch

Using this algorithm i can make very complex branching model, but my branches are always at latest commit position. It is just impossible to checkout specific branch at specific commit and derive new branch from the past.

Perhaps you solved that problem in react package? It sound to be real use case.

**Comment by nicoespeon** [comment] 2019-04-12 00:32
I see. 

So, when you build the graph manually, you don't really need that feature as you can control when you create the branch.

Now, when you're importing a JSON, it's different as you'd need to perform the commands in the correct order to generate the same graph. The way we currently handle this in the core library is by having the same data structure than the imported format (git2json). So we're basically bypassing the regular API to generate the graph. It's not ideal though, I'd like to enhance the regular API so we don't have that direct dependency. But still, it works.

In your scenario, I feel that `@gitgraph/core` should be able to do everything you need already, if you import a JSON generated by `git2json`. My understanding is that you need to build a Vue.js rendering library, that will render the graph based on the core computations. 

You would:
- instantiate `Gitgraph` from `@gitgraph/core`
- subscribe to the changes with `gitgraph.subscribe(render)`
- call `gitgraph.import(exported-graph.json)` 

The core will deal with the JSON file and translate that into rendered data. The role of the rendering lib is to make this data generate an actual SVG / Canvas / anything that will render in the browser. This, you can do with any framework (React, Angular, Vue.js…). It's a bit of work though, but you can get inspiration from existing rendering libs.

That's what we described in the core documentation: https://github.com/nicoespeon/gitgraph.js/tree/master/packages/gitgraph-core#developing-a-rendering-library

Does it sound like what you'd like to achieve? Or did I misunderstood something?

---

Also, I wonder if you could do something with the `@gitgraph/js` library now that it's out. It's vanilla JS. You just need to provide it an HTMLElement in which to render. You could embed that into a Vue.js component, and it should work fine!

For example, I did a React wrapper around the `@gitgraph/js` lib because I wanted to get it into our Storybook—was necessary because it can't handle different frameworks in the same runtime for now.

Here's the wrapper: https://github.com/nicoespeon/gitgraph.js/blob/cda0b6db3892ea6588681b7ad0868f886390a18b/packages/stories/src/helpers.tsx#L19-L38

And the usage: https://github.com/nicoespeon/gitgraph.js/blob/cda0b6db3892ea6588681b7ad0868f886390a18b/packages/stories/src/gitgraph-js/1-basic-usage.stories.tsx#L9-L22

You can see that inside `<GraphContainer>`, it's the regular `@gitgraph/js` behavior.

Could you create a Vue.js wrapper to embed `@gitgraph/js` into a Vue project?

**Comment by asmironov** [comment] 2019-04-29 12:48
>  Could you share more details about what you'd like to achieve? Do you have a use-case in mind that would require you to checkout a specific commit instead of a branch?

I'm building the graph manually and I need to illustrate the concept of support branches in the GitFlow model. These are branches created from specific commit. For example, we have a series of commits on master: one tagged `v1.0.0`, and other tagged `v1.1.0`, etc. Then we need to fix a bug in version 1.0.0. GitFlow says that we need to create a branch from the commit, tagged `v1.0.0`, and make our fixes on that branch. This should be possible with gitgraph.

**Comment by nicoespeon** [comment] 2019-05-09 01:35
Hi @asmironov 👋 

If you're building the graph manually, could you solve this by creating the branch "when" you want it to happen?

There is a temporal coupling, branch will either:
- be created at the HEAD when `gitgraph.branch("my-branch")` is called,
- be created at the latest commit of the parent branch you're giving through `gitgraph.branch({ name: "my-branch", from: "master" })` or `master.branch("my-branch")`

It's not perfect, but it's fine if you build graph manually since you have access to the whole timeline. You can create the branch when you want the branch to appear.

**Comment by nicoespeon** [comment] 2019-05-23 23:33
Hey @alvassin & @asmironov, I've got great news for you.

Thanks to @kohakukun's work (see #295), it's now possible to create a branch from a past commit. For that, you can pass the hash of the commit when you create the branch. 

You can use it like this

```js
const master = gitgraph.branch("master");

master
  .commit("Init project")
  .commit({ subject: "Add README", hash: "abc1234" })
  .commit("Add tests");

const myBranch = gitgraph.branch({
  name: "my-branch",
  from: "abc1234", // => hash of the commit we want to "checkout"
});

myBranch.commit("Start from old commit");
```

It will produce 

![image](https://user-images.githubusercontent.com/1094774/58292802-cd061000-7d90-11e9-965a-85891c6aea55.png)

I think it solves the root cause of this issue. Thus, I'm closing it. 
Feel free to re-open it (or create a new one) if you think there's something else to dig 👨‍🌾

**Closed by nicoespeon** 2019-05-23 23:33 UTC
Labels: :sparkles: Feature, :speech_balloon: Discussion
