### ISSUE TITLE
Support multiple tags per commit

### ISSUE THREAD

**Issue by nathan-alden** [nicoespeon/gitgraph.js#148] opened 2017-03-23 18:55 UTC
It seems that gitgraph doesn't support multiple tags per commit. This would be a useful enhancement for me. I'm modeling our CI system's tagging methodology on our repositories, and the same commit can end up with multiple tags.

**Comment by nicoespeon** [comment] 2017-03-24 07:45
That's correct, commits should handle (and display) multiple tags.

Thanks for the suggestion 👍

**Comment by nicoespeon** [comment] 2017-04-20 21:54
I just realized this is a duplicate of #143. I'm closing this issue, but the point is still noted 👍

**Closed by nicoespeon** 2017-04-20 21:54 UTC
Labels: 2 - feature
